- name: configure DB server
  hosts: localhost
  become: yes
  vars:
    login_host: 172.31.16.160
  vars_prompt:
  - name: MYSQL_root_pass
    prompt: please enter MYSQL root password
    private: no
  tasks:
  - name: install Mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql python dependencies
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_output

  - name: print output
    ansible.builtin.debug:
      msg: "output {{mysql_output}}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true 
  